/** Souq's fixed headings and buttons, in English and Arabic. Everything else comes from the settings or the menu. */
const en = {
  viewMenu: "View the menu",
  findUs: "Find us",
  signatureEyebrow: "Signature picks",
  signatureTitle: "The ones everybody orders",
  signatureText: "Start here if it is your first visit.",
  viewDetails: "View details",
  menuEyebrow: "Full menu",
  menuTitle: "Menu and prices",
  categories: "Menu categories",
  storyEyebrow: "Our story",
  since: "Since",
  galleryEyebrow: "Gallery",
  galleryTitle: "Inside {name}",
  reviewsEyebrow: "Reviews",
  reviewsTitle: "What our guests say",
  visitEyebrow: "Visit us",
  visitTitle: "Come by, we saved you a seat",
  address: "Address",
  whatsapp: "WhatsApp",
  email: "Email",
  getDirections: "Get directions",
  explore: "Explore",
  visit: "Visit",
  newsletter: "Newsletter",
  newsletterText: "New items and offers, straight to your inbox.",
  join: "Join",
  rights: "All rights reserved.",
  mainNav: "Main",
  photo: "Photo {n} of {name}",
};

export type SouqCopy = typeof en;

const ar: SouqCopy = {
  viewMenu: "تصفح القائمة",
  findUs: "موقعنا",
  signatureEyebrow: "اختياراتنا المميزة",
  signatureTitle: "الأصناف التي يطلبها الجميع",
  signatureText: "ابدأ من هنا إن كانت زيارتك الأولى.",
  viewDetails: "التفاصيل",
  menuEyebrow: "القائمة الكاملة",
  menuTitle: "القائمة والأسعار",
  categories: "أقسام القائمة",
  storyEyebrow: "قصتنا",
  since: "منذ",
  galleryEyebrow: "الصور",
  galleryTitle: "من داخل {name}",
  reviewsEyebrow: "آراء الضيوف",
  reviewsTitle: "ماذا يقول ضيوفنا",
  visitEyebrow: "زورونا",
  visitTitle: "تفضلوا بزيارتنا، مكانكم محفوظ",
  address: "العنوان",
  whatsapp: "واتساب",
  email: "البريد الإلكتروني",
  getDirections: "الاتجاهات",
  explore: "تصفح",
  visit: "زيارة",
  newsletter: "النشرة البريدية",
  newsletterText: "أصناف جديدة وعروض تصلك إلى بريدك.",
  join: "اشترك",
  rights: "جميع الحقوق محفوظة.",
  mainNav: "الرئيسية",
  photo: "الصورة {n} من {name}",
};

export const souqCopy = (locale: string): SouqCopy => (locale === "ar" ? ar : en);
