<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Storefront.Infrastructure\Storefront.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Storefront.Web.IntegrationTests" />
  </ItemGroup>
</Project>
